### ISSUE TITLE
Node selection button appearance broken in DOM inspector

### ISSUE THREAD

**Issue by ghost** [Lootyhoof/tangomoon#1]
The node selection buttons do not show with their proper styles applied, as shown in the image below.

![1](https://cloud.githubusercontent.com/assets/11385622/9021811/2325c738-3875-11e5-8352-b0aecd4d87d8.png)

**Comment by Lootyhoof** [comment]
Fixed in bba4a018b884ddc0dead13eaed84ed14198ddba8. Thanks for the report!
