### ISSUE TITLE
Pale Moon button question

### ISSUE THREAD

**Issue by Gittyperson** [Lootyhoof/tangomoon#2]
Not sure if this is a glitch or by design, left of the 'Pale Moon' text:

![Pale Moon button](https://user-images.githubusercontent.com/7165208/59298122-79515d00-8c92-11e9-9f94-05267cdebd7a.png)

Windows 10, Pale Moon 28.5.2, Tangomoon 2.4.0

**Comment by Lootyhoof** [comment]
It's by design. It's meant to be a stylised background using the "[start here](https://commons.wikimedia.org/wiki/Tango_icons#/media/File:Start-here.svg)" icons from the Tango Icon Set.

There's a similar style on Tangerinemoon, too, using the Ubuntu icon. These are all by design.
